name: ci

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: go build -v cmd/main.go

      - name: Test
        run: go test -v ./...

  check-readme-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Ensure the readme is formatted (make format-readme)
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_options: --write README.md
